name: Deploy to InfinityFree

on:
  push:
    branches:
      - main  # Trigger deploy on push to main branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload to InfinityFree FTP
        uses: SamKirkland/FTP-Deploy-Action@main
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./   # Root directory of your repo
          server-dir: /htdocs/  # InfinityFree document root folder
